# Generated by Django 3.1.4 on 2020-12-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('CourierId', models.AutoField(primary_key=True, serialize=False)),
                ('MessageId', models.CharField(max_length=100)),
                ('FromName', models.CharField(max_length=100)),
                ('StudentName', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('RollNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PODnumber', models.CharField(max_length=50)),
                ('Received_On', models.DateTimeField(auto_now_add=True)),
                ('OtherInformation', models.CharField(blank=True, max_length=100, null=True)),
                ('Collected', models.BooleanField(blank=True, default=False, null=True)),
                ('Collected_On', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-Received_On'],
            },
        ),
    ]
