# Generated by Django 3.1.4 on 2021-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MessageId',
        ),
        migrations.AddField(
            model_name='post',
            name='Notified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
