# Generated by Django 3.1.4 on 2021-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentMail', models.CharField(max_length=50)),
                ('ChildMail', models.CharField(max_length=50)),
                ('HashedPassword', models.CharField(max_length=70)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumberMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentMail', models.CharField(max_length=50)),
                ('ChildNumber', models.CharField(max_length=50)),
                ('HashedPassword', models.CharField(max_length=70)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
