# Generated by Django 3.1.4 on 2021-03-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='isAdmin',
        ),
    ]
